# Site Settings
title: "황준홍 | 개발자 포트폴리오"
description: "사용자 친화적인 서비스를 만드는 7년차 개발자 황준홍의 포트폴리오"
baseurl: ""
url: "https://hwangjunhong.github.io"

# Personal Information
name: "황준홍"
title: "7년차 풀스택 개발자"
email: "ghkdwnsghd1@naver.com"
github: "hwangjunhong"
blog: "https://jjjhong.tistory.com/"

# Site Configuration
permalink: /:categories/:title/
timezone: Asia/Seoul
encoding: utf-8

# Build Settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
